name: Simple CI for Spring Boot

on:
  push:
    branches:
      - main  # ou 'master' si ta branche s'appelle comme ça

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Print success message
        run: echo "Build and tests completed successfully!"
